- name: Install Java 8 using YUM.
  apt:
    name: "{{java.VERSION}}"
    state: present
  become: true

#- name: Correct the alternatives to change default Java version.
 # alternatives:
  #  name: java
   # path: "{{java.ALTERNATIVES}}"

- name: Download Jenkins repo apt URL for  
  get_url:
    url: "{{jenkins.repo_URL}}"
    dest: /etc/apt/sources.list.d/jenkins.list
  become: true

- name: Import GPG Key
  apt_key:
    state: present
    key: "{{jenkins.gpg_key}}"
  
- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Change Jenkins JAVA options
  lineinfile: 
    dest=/etc/sysconfig/jenkins
    regexp=^JENKINS_JAVA_OPTIONS=
    line=JENKINS_JAVA_OPTIONS="{{jenkins.JAVA_OPTIONS}}"
  become: true

- name: Start Jenkins service and enable on boot
  service:
    name: jenkins
    state: started
    enabled: yes