---
- hosts: all
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install Docker-compose Module for Python
      pip:
        name: docker-compose
 
    - name: Start docker services
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
 
    - name: Get from GitHub docker-compose LAMP project
      ansible.builtin.git:
        repo: https://github.com/zinchenko-ihor/docker-compose-lamp.git
        dest: /home/ubuntu/docker-compose-lamp
        clone: yes
        version: master             
   
    - name: Run "docker-compose up" 
      community.docker.docker_compose:
        project_src: /home/ubuntu/docker-compose-lamp/
        build: yes
      register: output
