name: Integration
env:
 LOGIN: ${{ secrets.DOCKER_LOGIN }}
 NAME: ${{ secrets.DOCKER_NAME }}
 
on:
  push:
    branches: [ master ]
  
jobs:
  
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: Login to docker.io
       run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
     - uses: actions/checkout@master
     - name: Build image
       run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
     - name: Push image to docker.io
       run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
