name: CI-CD-to-AWS
env:
 EB_PACKAGE_S3_BACKET_NAME : "zinchenko-ihor"
 EB_APPLICATION_NAME       : "zinchenko-ihor"
 EB_ENVIRONMENT_NAME       : "Zinchenkoihor-env"
 DEPLOY_PACKAGE_NAME       : "docker_{{ github.sha }}"
 AWS_REGION_NAME           : "eu-central-1"
on:
 
  push:
    branches: [ master ]
   
jobs:
  
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repository
        uses: actions/checkout@v2
     
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env. DEPLOY_PACKAGE_NAME }}:$(date +%s)
