name: Docker Image CI
env:
  UNAME : "Zinchenko"
  DOCK : "${{ github.sha }}"
on:
  push:
    branches: [ master ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    - name: exec to container
      run: docker exec -it ${{ env.DOCK }} bash
      
    - name: message
      run: echo "DEVOPS= ${{ env.UNAME }} " > /var/www/html/index.html
      
      
