name: test
 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run message
        run: echo "Hello, world!"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Hi, test is good,"
          echo "test, and deploy your project".
